---
title: "Base de datos"
author: "Cynthia Villanueva Gaston"
date: "10/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("~/Estadística 2/Trabajo grupal/Base de datos")
```

```{r}
library(rio)
modulo2=import("Modulo 2.sav")
modulo3=import("Modulo 3.sav")
modulo4=import("Modulo 4.sav")
modulo5=import("Modulo 5.sav")
modulo6=import("Modulo 6.sav")
modulo7=import("Modulo 7.sav")
```

```{r}
str(modulo2$NOMBDEPA)
```

```{r}
library(dplyr)
```

```{r}
modulo2 = filter(modulo2, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P204, P205_A) 
```

```{r}
modulo3 = filter(modulo3, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P304,P315_1,P315_2, P315_3, P315_4, P315_5, P315_6, P315_7, P315_8, P315_9, P315_10) 
```

```{r}
modulo4 = filter(modulo4, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P401_1, P401_2, P401_3, P401_4, P401_5, P408_1, P408_2, P408_3,P408_4, P408_5, P408_6 ) 
```

```{r}
modulo5 = filter(modulo5, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P501, P510, P512, P513  ) 
```

```{r}
modulo6 = filter(modulo6, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P604_1, P604_2, P604_3, P604_4, P604_5, P604_6, P604_7, P604_8, P604_9, P604_10, P604_11, P609, P611, P614_MON, P614_ESP, P615_MON, P615_ESP, P616_MON, P616_ESP) 
```

```{r}
modulo7 = filter(modulo7, NOMBDEPA == "CALLAO" | NOMBDEPA == "LIMA")  %>%  select(., NOMBDEPA, VIVIENDA, HOGAR, CODPERSO, P701)
```

```{r}
base = modulo2 %>% left_join(modulo3)
base = base %>% left_join(modulo4)
base = base %>% left_join(modulo5)
base = base %>% left_join(modulo6)
base = base %>% left_join(modulo7)
```


```{r}
base$P204=as.factor(base$P204)
str(base$P204)
levels(base$P204)=c("Hombre", "Mujer")
table(base$P204)
```

```{r}
base$P304=as.factor(base$P304)
levels(base$P304)=c("Si", "No")
table(base$P304)
```

```{r}
base$P510=as.factor(base$P510)
levels(base$P510)=c("Si", "No")
table(base$P510)
```

```{r}
base$P512=as.factor(base$P512)
levels(base$P512)=c("Indígena", "Afrodescendiente", "Blanco/a", "Mestizo/a", "Grupo étnico", "Otro", "No sabe")
table(base$P512)
```

```{r}
base$P513=as.factor(base$P513)
levels(base$P513)=c("Heterosexual", "Gay", "Lesbiana", "Bisexual", "Pansexual", "Asexual", "Otro", "No sabe")
table(base$P513)
```

```{r}
base$P609=as.factor(base$P609)
levels(base$P609)=c("Si", "No")
table(base$P609)
```

```{r}
base$P701=as.factor(base$P701)
levels(base$P701)=c("Si", "No")
table(base$P701)
```

```{r}
head(base)
```

```{r}
base_editada=data.frame(base)
```


```{r}
base_editada$P315 <- names(base_editada[8:16])[max.col(base_editada[8:16])]
```

```{r}
base_editada$P315 = recode(base_editada$P315, P315_1 = "Visa de turista" , P315_2 = "Visa de trabajo", P315_3 =  "Visa de estudiante", P315_4 = "Solicitante de PTP", P315_5 = "Con Permiso Temporal de Trabajo – PTP", P315_6 = "Solicitante de refugio", P315_7= "Refugiado", P315_8="Carnet de Extranjería", P315_9="DNI", P315_10= "Otra situación")
```

```{r}
base_editada$P401 <- names(base_editada[18:22])[max.col(base_editada[18:22])]
```

```{r}
base_editada$P401 = recode(base_editada$P401, P401_1 = "ESSALUD" , P401_2 = "Seguro Privado de Salud", P401_3 =  "Seguro Integral de Salud - SIS", P401_4 = "Otro", P401_5 = "No está afiliado")
```

```{r}
base_editada$P408_1=as.factor(base_editada$P408_1)
levels(base_editada$P408_1)=c("Si", "No")
table(base_editada$P408_1)
```


```{r}
base_editada$P408_2=as.factor(base_editada$P408_2)
levels(base_editada$P408_2)=c("Si", "No")
table(base_editada$P408_2)
```

```{r}
base_editada$P408_3=as.factor(base_editada$P408_3)
levels(base_editada$P408_3)=c("Si", "No")
table(base_editada$P408_3)
```

```{r}
base_editada$P408_4=as.factor(base_editada$P408_4)
levels(base_editada$P408_4)=c("Si", "No")
table(base_editada$P408_4)
```

```{r}
base_editada$P408_5=as.factor(base_editada$P408_5)
levels(base_editada$P408_5)=c("Si", "No")
table(base_editada$P408_5)
```

```{r}
base_editada$P408_6=as.factor(base_editada$P408_6)
levels(base_editada$P408_6)=c("Si", "No")
table(base_editada$P408_6)
```


```{r}
base_editada$P501=as.factor(base_editada$P501)
base_editada$P501 = recode(base_editada$P501, "1" = "Sin nivel" , "2" = "Preescolar", "3" =  "Educación Básica Incompleta", "4" = "Educación Básica Completa", "5" = "Educación Media Diversificada Incompleta ", "6"="Educación Media Diversificada Completa", "7"="Técnico Superior Incompleta", "8"="Técnico Superior Completa", "9"="Superior Universitaria Incompleta", "10"="Superior Universitaria Completa", "11"="Maestría/ Doctorado")
table(base_editada$P501)
```


```{r}
base_editada$P604_1[base_editada$P604_1 == 0] <- NA

base_editada$P604_1=as.factor(base_editada$P604_1)
levels(base_editada$P604_1)=c("Si", "No")
table(base_editada$P604_1)
```

```{r}
base_editada$P604_2[base_editada$P604_2 == 0] <- NA

base_editada$P604_2=as.factor(base_editada$P604_2)
levels(base_editada$P604_2)=c("Si", "No")
table(base_editada$P604_2)
```

```{r}
base_editada$P604_3[base_editada$P604_3 == 0] <- NA

base_editada$P604_3=as.factor(base_editada$P604_3)
levels(base_editada$P604_3)=c("Si", "No")
table(base_editada$P604_3)
```

```{r}
base_editada$P604_4[base_editada$P604_4 == 0] <- NA

base_editada$P604_4=as.factor(base_editada$P604_4)
levels(base_editada$P604_4)=c("Si", "No")
table(base_editada$P604_4)
```

```{r}
base_editada$P604_5[base_editada$P604_5 == 0] <- NA

base_editada$P604_5=as.factor(base_editada$P604_5)
levels(base_editada$P604_5)=c("Si", "No")
table(base_editada$P604_5)
```

```{r}
base_editada$P604_6[base_editada$P604_6 == 0] <- NA

base_editada$P604_6=as.factor(base_editada$P604_6)
levels(base_editada$P604_6)=c("Si", "No")
table(base_editada$P604_6)
```

```{r}
base_editada$P604_7[base_editada$P604_7 == 0] <- NA

base_editada$P604_7=as.factor(base_editada$P604_7)
levels(base_editada$P604_7)=c("Si", "No")
table(base_editada$P604_7)
```

```{r}
base_editada$P604_8[base_editada$P604_8 == 0] <- NA

base_editada$P604_8=as.factor(base_editada$P604_8)
levels(base_editada$P604_8)=c("Si", "No")
table(base_editada$P604_8)
```

```{r}
base_editada$P604_9[base_editada$P604_9 == 0] <- NA

base_editada$P604_9=as.factor(base_editada$P604_9)
levels(base_editada$P604_9)=c("Si", "No")
table(base_editada$P604_9)
```

```{r}
base_editada$P604_10[base_editada$P604_10 == 0] <- NA

base_editada$P604_10=as.factor(base_editada$P604_10)
levels(base_editada$P604_10)=c("Si", "No")
table(base_editada$P604_10)
```

```{r}
base_editada$P604_11[base_editada$P604_11 == 0] <- NA

base_editada$P604_11=as.factor(base_editada$P604_11)
levels(base_editada$P604_11)=c("Si", "No")
table(base_editada$P604_11)
```

```{r}
base_editada$P315_1 = NULL 
base_editada$P315_2 = NULL 
base_editada$P315_3 = NULL 
base_editada$P315_4 = NULL 
base_editada$P315_5 = NULL 
base_editada$P315_6 = NULL 
base_editada$P315_7 = NULL 
base_editada$P315_8 = NULL 
base_editada$P315_9 = NULL 
base_editada$P315_10 = NULL 
```

```{r}
base_editada$P401_1 = NULL
base_editada$P401_2 = NULL
base_editada$P401_3 = NULL
base_editada$P401_4 = NULL
base_editada$P401_5 = NULL
```

```{r}
library (openxlsx)
library(readxl)
library(writexl)
write.xlsx(base_editada, "Base de datos ENPOVE.xlsx")
```

